
-- User
INSERT INTO user (username, token, status, password, creation_date, birth_date, language, wins, losses, winlossratio, avatar_url)
VALUES
    ('user1', 'token1', 1, '111', '2024-01-01', '2000-01-01', 'en', 20, 13, 1.335, '/images/avatar/villager.png'),
    ('user2', 'token2', 1, '222', '2024-01-02', '2000-01-02', 'zh', 40, 60, 0.748, '/images/avatar/wolf.png'),
    ('user3', 'token3', 1, '333', '2024-01-03', '2000-01-03', 'de', 36, 27, 0.571, '/images/avatar/demon.png'),
    ('user4', 'token4', 1, '444', '2024-01-04', '2000-01-04', 'ja', 11, 1, 1.263, '/images/avatar/frightened_villager.png'),
    ('user5', 'token5', 1, '555', '2024-01-05', '2000-01-05', 'fr', 22, 22, 0.846, '/images/avatar/good_wolf.png'),
    ('user6', 'token6', 1, '111', '2024-01-06', '2000-01-06', 'es', 38, 12, 2.051, '/images/avatar/hunter.png'),
    ('user7', 'token7', 1, '111', '2024-01-07', '2000-01-07', 'hi', 7, 2, 1.521, '/images/avatar/knight.png'),
    ('user8', 'token8', 1, '111', '2024-01-08', '2000-01-08', 'ar', 62, 22, 2.158, '/images/avatar/magician.png'),
    ('user9', 'token9', 1, '111', '2024-01-09', '2000-01-09', 'pt', 108, 2, 2.986, '/images/avatar/nobody.png'),
    ('user10', 'token10', 1, '111', '2024-01-10', '2000-01-10', 'bn', 24, 5, 2.037, '/images/avatar/ogre.png'),
    ('user11', 'token11', 1, '111', '2024-01-11', '2000-01-11', 'ru', 89, 43, 2.103, '/images/avatar/suspicious_dude.png');
-- Theme
INSERT INTO THEME (name)
VALUES
    ('Animal'),
    ('Food'),
    ('Sports'),
    ('Pokemon'),
    ('Video Games'),
    ('Movies'),
    ('Superheroes'),
    ('Countries');

-- Words
INSERT INTO WORD_PAIR (theme_id, first_word, second_word)
VALUES
    (1, 'Dog', 'Cat'),
    (1, 'Elephant', 'Giraffe'),
    (1, 'Crow', 'Swan'),
    (1, 'Mouse', 'Owl'),
    (1, 'Ant', 'Spider'),
    (1, 'Shark', 'Dolphin'),
    (1, 'Frog', 'Horse'),
    (1, 'Cow', 'Sheep'),
    (1, 'Wolf', 'Lion'),
    (1, 'Snake', 'Crab'),
    (1, 'Bear', 'Moose'),
    (1, 'Chameleon', 'Fly'),
    (1, 'Fox', 'Hedgehog'),
    (2, 'Apple', 'Orange'),
    (2, 'Coffee', 'Tea'),
    (2, 'Pasta', 'Pizza'),
    (2, 'Cereal', 'Sushi'),
    (2, 'Ramen', 'Rice'),
    (2, 'Raclette', 'Hamburger'),
    (2, 'Sandwich', 'Cookie'),
    (2, 'Cake', 'Carrot'),
    (2, 'Mango', 'Onion'),
    (2, 'Salad', 'Steak'),
    (2, 'Spinach', 'Spaghetti'),
    (2, 'Lasagna', 'French Fries'),
    (2, 'Chicken Nuggets', 'Ice Cream'),
    (2, 'Chocolate', 'Bubble Gum'),
    (2, 'Lolipop', 'Cotton Candy'),
    (2, 'Potato', 'Kiwi'),
    (2, 'Banana', 'Strawberry'),
    (3, 'Basketball', 'Soccer'),
    (3, 'Rugby', 'Golf'),
    (3, 'Tennis', 'Polo'),
    (3, 'Long Jump', 'Pole Vault'),
    (3, 'Ice Hockey', 'Chess'),
    (3, 'Floorball', 'Swimming'),
    (3, 'Marathon', 'Skiing'),
    (3, 'Biking', 'Jogging'),
    (3, 'Formula 1', 'Gymnastics'),
    (3, 'Yoga', 'Cricket'),
    (3, 'Baseball', 'Karate'),
    (4, 'Charizard', 'Pikachu'),
    (4, 'Eevee', 'Mew'),
    (4, 'Mewto', 'Bulbasaur'),
    (4, 'Squirtle', 'Meowth'),
    (4, 'Jigglypuff', 'Gyrados'),
    (4, 'Gengar', 'Machomp'),
    (4, 'Kyogre', 'Rayquaza'),
    (4, 'Groudon', 'Gengar'),
    (5, 'Pokemon', 'The Sims'),
    (5, 'Tetris', 'Pong'),
    (5, 'Pac Man', 'Donkey Kong'),
    (5, 'Super Mario', 'Call of Duty'),
    (5, 'Age of Empires', 'Overwatch'),
    (5, 'Minecraft', 'Roblox'),
    (5, 'Mortal Kombat', 'Mario Kart'),
    (5, 'Super Smash Bros', 'Halo'),
    (5, 'The Legend of Zelda', 'GTA'),
    (5, 'Fortnite', 'The Elder Scrolls'),
    (5, 'League of Legends', 'Counter Strike'),
    (5, 'World of Warcraft', 'Destiny'),
    (5, 'Red Dead Redemption', 'Fifa'),
    (5, 'Rocket League', 'GeoGuessr'),
    (5, 'Wordle', 'Portal'),
    (5, 'Half Life', 'Watchdogs'),
    (6, 'Titanic', 'Pycho'),
    (6, 'Star Wars', 'Harry Potter'),
    (6, 'The Lord of the Rings', 'The Matrix'),
    (6, 'The Shawshank Redemption', 'The Godfather'),
    (6, 'Avengers', 'Forrest Gump'),
    (6, 'Jurassic Park', 'Inception'),
    (6, 'Pulp Fiction', 'The Lion king'),
    (6, 'Ice Age', 'Finding Nemo'),
    (6, 'Avatar', 'Inglourious Basterds'),
    (6, 'Saving Private Ryan', 'The Silence of the Lambs'),
    (6, 'Toy Story', 'Fight Club'),
    (6, 'Interstellar', '2001: A Space Odyssey'),
    (6, 'Back to the Future', 'Shrek'),
    (7, 'Superman', 'Batman'),
    (7, 'Wonder Woman', 'Aquaman'),
    (7, 'The Flash', 'Iron Man'),
    (7, 'Thor', 'Captain America'),
    (7, 'Spiderman', 'Magneto'),
    (7, 'Deadpool', 'Wolverine'),
    (7, 'Black Panther', 'The Hulk'),
    (7, 'Green Lantern', 'Black Widow'),
    (7, 'Hawkeye', 'Storm'),
    (7, 'Professor X', 'Dr. Strange'),
    (7, 'Antman', 'Scarlet Witch'),
    (7, 'Vision', 'Rohrschach'),
    (7, 'Doctor Manhattan', 'Catwoman'),
    (7, 'Robin', 'Colossus'),
    (8, 'Switzerland', 'Germany'),
    (8, 'Italy', 'Spain'),
    (8, 'France', 'Russia'),
    (8, 'USA', 'Mexico'),
    (8, 'China', 'Japan'),
    (8, 'South korea', 'Thailand'),
    (8, 'Australia', 'Brazil'),
    (8, 'Egypt', 'Marocco'),
    (8, 'South Africa', 'Canada'),
    (8, 'Bolivia', 'Colombia'),
    (8, 'Cuba', 'Portugal'),
    (8, 'England', 'Ireland'),
    (8, 'Sweden', 'Vatican City'),
    (8, 'Norway', 'Netherlands'),
    (8, 'Croatia', 'India'),
    (8, 'Iceland', 'Austria');
